spring.application.name=GrandTickAutoVi

spring.ai.google.genai.api-key=YOUR_API_KEY

spring.datasource.url=jdbc:mysql://localhost:3306/grand_tick_auto_news

spring.datasource.username=USERNAME
spring.datasource.password=PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
