spring.application.name=ECOM

spring.datasource.url = JDBC:mysql://localhost:3306/personal

spring.datasource.username = root
spring.datasource.password = Hope

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
